import streamlit as st
import tempfile
import os
import merger  # Import your original untouched merger.py file

st.set_page_config(page_title="GCode Merger", layout="centered")

st.markdown(
    """
    <style>
    div.stDownloadButton > button,
    div.stButton > button {
        background-color: #2e7d32 !important;
        color: white !important;
        border: 1px solid #2e7d32 !important;
    }
    div.stDownloadButton > button:hover,
    div.stButton > button:hover {
        background-color: #1b5e20 !important;
        border-color: #1b5e20 !important;
    }
    </style>
    """,
    unsafe_allow_html=True,
)

# ==============================================================================
# USER GUIDE DIALOG (Hidden by default, acts like a popup modal)
# ==============================================================================
@st.dialog("User Guide — v1.0", width="large")
def show_help():
    st.markdown("""
    ## 📖 User Guide

    ### **Step 1 — FullControl G-code (.gcode)**
    Upload the `.gcode` file exported from **FullControl.xyz** or FullControl Python. This file contains the custom toolpath generated by FullControl and usually does **not** include your printer's startup and shutdown procedures.

    ---

    ### **Step 2 — Placeholder Model**
    If you don't already have a slicer-generated G-code for an object with the same dimensions, create a simple placeholder model (such as a box) with the **same width, depth, and height** as your FullControl model.

    Slice this placeholder using **Creality Print** (or another compatible slicer) with your printer profile.

    > ⚠️ The placeholder only needs to match the overall dimensions. It does **not** need to match the actual geometry.

    ---

    ### **Step 3 — Slicer G-code Template (.gcode)**
    Upload the G-code generated by your slicer from the placeholder model.

    This file provides all printer-specific startup and shutdown procedures, including features such as:

    - Start and End macros
    - Bed heating
    - Nozzle heating
    - Auto bed leveling (if enabled)
    - Purge line
    - Homing
    - Other printer-specific Klipper macros and initialization commands

    ---

    ### **Automatic Centering**
    The application automatically calculates the bounding box of your FullControl toolpath and centers it on the print bed.

    - ✅ Only **X** and **Y** coordinates are shifted.
    - ✅ **Z coordinates are never modified**, making it safe for non-planar printing.
    - ✅ Only absolute `G0` and `G1` movement commands (`G90`) are adjusted.

    ---

    ### **Important Notes**

    - Always use a slicer G-code generated for **the same printer** and **approximately the same model dimensions**.
    - Do **not** remove your printer's startup or shutdown macros.
    - The merged file preserves your printer's initialization sequence while replacing the printing toolpath with the FullControl toolpath.
    - If temperatures differ between the FullControl file and the slicer template, the printer will follow the temperatures defined in the slicer template.

    ---

    ### **Compatibility**

    This application is designed for **Creality printers running Klipper firmware**.

    ✅ Currently tested on:
    - **Creality K2 Basic**

    Other Creality Klipper-based printers may also work, but they have **not yet been tested**.

    ---

    ### **Feedback & Support**

    If you encounter any issues, have suggestions, or successfully use this tool on another Creality Klipper printer, I'd love to hear from you!

    📩 TikTok: **@aapisme**
    """)

# ==============================================================================
# MAIN HEADER
# ==============================================================================
# Layout for Title on the left, Help button on the right
col_title, col_help = st.columns([5, 1])
with col_title:
    st.title("GCode Merger")
    st.markdown("**FullControl G-Code Merger for Creality Klipper Printers**")
    st.markdown("by AAPISME — [TikTok](https://www.tiktok.com/@aapisme) | [GitHub](https://github.com/zhafarullah/Creality-Gcode-Merger)")
with col_help:
    st.write("")  # Vertical spacer
    if st.button("User Guide", use_container_width=True):
        show_help()

st.divider()

fc_data = None
fc_bbox = None
cr_data = None

# ==============================================================================
# STEP 1: FULLCONTROL G-CODE
# ==============================================================================
st.subheader("1. FullControl G-Code")
st.markdown("*Upload the G-code generated from the fullcontrol.xyz website or FullControl Python.*")
fc_file = st.file_uploader(
    "Select FullControl .gcode file",
    type=["gcode", "gco", "g"],
    key="fc",
    accept_multiple_files=False,
)

if fc_file:
    lines = fc_file.getvalue().decode("utf-8").splitlines()
    fc_data = merger.parse_fullcontrol(lines)
    fc_bbox = merger.find_bounding_box_3d(fc_data.toolpath)

    st.success("File Loaded Successfully")
    metric_cols = st.columns(4)
    metric_cols[0].markdown(f"**Toolpath:**\n{len(fc_data.toolpath)} lines")
    metric_cols[1].markdown(f"**Hotend:**\n{fc_data.extruder_temp}°C")
    metric_cols[2].markdown(f"**Bed:**\n{fc_data.bed_temp}°C")
    metric_cols[3].markdown(f"**Fan:**\nS{fc_data.fan_speed} ({round(fc_data.fan_speed / 2.55)}%)")

    if fc_data.has_primer:
        st.caption(f"Primer: {len(fc_data.primer)} lines")

    for w in fc_data.warnings:
        st.warning(w)

st.write("---")

# ==============================================================================
# STEP 2: STL PLACEHOLDER
# ==============================================================================
st.subheader("2. Generate Placeholder STL")
st.markdown("*Download the STL and import it into your Creality Print or Orca Slicer.*")

if fc_file and fc_bbox:
    min_x, max_x, min_y, max_y, min_z, max_z = fc_bbox
    w, d, h = max_x - min_x, max_y - min_y, max_z - min_z
    model_name = fc_file.name.split('.')[0]

    st.info(f"**Detected FullControl Bounding Box:** Width: {w:.2f} mm, Depth: {d:.2f} mm, Height: {h:.2f} mm")
    # Auto-generate the STL silently in the background
    with tempfile.NamedTemporaryFile(delete=False, suffix=".stl") as tmp:
        tmp_path = tmp.name
    merger.generate_bbox_stl(tmp_path, w, d, h, model_name=model_name)

    with open(tmp_path, "rb") as f:
        stl_bytes = f.read()

    # User only sees the ready-to-download button
    st.download_button(
        label="Download Placeholder STL",
        data=stl_bytes,
        file_name=f"{model_name}_bbox.stl",
        mime="model/stl",
        type="secondary"
    )
    os.remove(tmp_path)
else:
    st.info("Load a FullControl file in Step 1 to automatically generate the STL placeholder.")

st.write("---")

# ==============================================================================
# STEP 3: SLICER G-CODE TEMPLATE
# ==============================================================================
st.subheader("3. Slicer G-Code Template")
st.markdown("*Export the G-code from your slicer using the STL placeholder, and upload it below.*")
cr_file = st.file_uploader(
    "Select Slicer .gcode file",
    type=["gcode", "gco", "g"],
    key="cr",
    accept_multiple_files=False,
)

if cr_file:
    lines = cr_file.getvalue().decode("utf-8").splitlines()
    cr_data = merger.parse_creality(lines)

    st.success("File Loaded Successfully")
    metric_cols2 = st.columns(4)
    metric_cols2[0].markdown(f"**Start seq:**\n{len(cr_data.start_seq)} lines")
    metric_cols2[1].markdown(f"**End seq:**\n{len(cr_data.end_seq)} lines")
    metric_cols2[2].markdown(f"**Bed:**\n{cr_data.bed_temp}°C")
    if cr_data.chamber_temp:
        metric_cols2[3].markdown(f"**Chamber:**\n{cr_data.chamber_temp}°C")

    if fc_data:
        nozzle_delta = abs(fc_data.extruder_temp - cr_data.extruder_temp)
        bed_delta = abs(fc_data.bed_temp - cr_data.bed_temp)

        st.markdown("**Temperature Comparison**")
        temp_cols = st.columns(2)
        temp_cols[0].markdown(
            f"**FullControl**\n"
            f"- Nozzle: {fc_data.extruder_temp}°C\n"
            f"- Bed: {fc_data.bed_temp}°C"
        )
        temp_cols[1].markdown(
            f"**Slicer template**\n"
            f"- Nozzle: {cr_data.extruder_temp}°C\n"
            f"- Bed: {cr_data.bed_temp}°C"
        )

        if nozzle_delta > 10 or bed_delta > 10:
            st.warning(
                "Temperature values differ. The printer will use the slicer template settings for the final merge."
            )
        else:
            st.success(
                "Temperature values are aligned. The merged file will keep the slicer template temperatures."
            )

    for w in cr_data.warnings:
        st.warning(w)

st.write("---")

# ==============================================================================
# STEP 4: OPTIONS & MERGE
# ==============================================================================
st.subheader("4. Options & Merge")
st.markdown("*Configure the options below, then click merge.*")

opt_col1, opt_col2 = st.columns(2)

with opt_col1:
    st.markdown("**General Options:**")
    opt_primer = st.checkbox("Include FullControl primer", value=False, help="Creality already ran a purge line (usually not needed)")
    opt_footer = st.checkbox("Include FullControl footer comments", value=True)

with opt_col2:
    st.markdown("**Centering Options:**")
    opt_center = st.checkbox("Automatically center the toolpath on the bed (X & Y)", value=True)

    bed_cols = st.columns(2)
    bed_w = bed_cols[0].number_input("Bed Width (mm)", value=260.0, step=10.0)
    bed_h = bed_cols[1].number_input("Bed Depth (mm)", value=260.0, step=10.0)

# Live Centering Preview Logic
if opt_center and fc_bbox:
    min_x, max_x, min_y, max_y, _, _ = fc_bbox
    mw, mh = max_x - min_x, max_y - min_y
    cx, cy = (min_x + max_x) / 2, (min_y + max_y) / 2
    ox, oy = (bed_w / 2) - cx, (bed_h / 2) - cy

    sx = '+' if ox >= 0 else ''
    sy = '+' if oy >= 0 else ''

    if min_x + ox < -0.1 or max_x + ox > bed_w + 0.1:
        st.error(f"Model ({mw:.1f} mm) is wider than the bed ({bed_w:.0f} mm)!")
    elif min_y + oy < -0.1 or max_y + oy > bed_h + 0.1:
        st.error(f"Model ({mh:.1f} mm) is deeper than the bed ({bed_h:.0f} mm)!")
    else:
        st.success(f"Auto-Center Preview: Model will be centered automatically. Offset X{sx}{ox:.2f} Y{sy}{oy:.2f} mm to fit exactly in the center.")

st.write("")  # Vertical spacer

# ==============================================================================
# BIG MERGE BUTTON
# ==============================================================================
if fc_data and cr_data:
    if st.button("MERGE G-CODE", type="primary", use_container_width=True):
        with st.spinner("Merging G-Code files..."):
            toolpath = fc_data.toolpath
            ci = None

            # Apply Centering using original logic
            if opt_center:
                toolpath, ci = merger.apply_centering(toolpath, float(bed_w), float(bed_h))

            # Assemble output using original logic
            out_lines = merger.assemble_output(
                cr_path=cr_file.name,
                fc_path=fc_file.name,
                cr=cr_data,
                fc=fc_data,
                toolpath=toolpath,
                skip_primer=not opt_primer,
                include_footer=opt_footer,
                center_info=ci,
                bed_w=float(bed_w),
                bed_h=float(bed_h)
            )

            merged_gcode = '\n'.join(out_lines) + '\n'
            filesize_mb = len(merged_gcode.encode('utf-8')) / (1024 * 1024)

            if ci:
                offset_x = ci.offset_x
                offset_y = ci.offset_y
            else:
                offset_x = 0.0
                offset_y = 0.0

            sx = '+' if offset_x >= 0 else ''
            sy = '+' if offset_y >= 0 else ''

            st.markdown("### ✅ Merge Completed")
            st.markdown("Merged successfully.")
            st.markdown(f"**Output size**<br>{filesize_mb:.2f} MB", unsafe_allow_html=True)
            st.markdown(f"**Center offset**<br>X {sx}{offset_x:.1f}<br>Y {sy}{offset_y:.1f}", unsafe_allow_html=True)

            st.download_button(
                label="[ Download Merged G-Code ]",
                data=merged_gcode,
                file_name=f"merged_{fc_file.name}",
                mime="text/plain",
                type="primary",
                use_container_width=True
            )
else:
    st.button("MERGE G-CODE", type="primary", use_container_width=True, disabled=True)
    st.info("Please complete Step 1 and Step 3 to enable merging.")